CREATE DATABASE IF NOT EXISTS LOCATION_VOITURES
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE LOCATION_VOITURES;

-- ====================================================================================
-- TABLE TYPEVEHICULE
-- ====================================================================================
CREATE TABLE TYPEVEHICULE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    CATEGORIE VARCHAR(50) NOT NULL,
    PRIXBASEJOURNALIER DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    DATECREATION DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ====================================================================================
-- TABLE UTILISATEUR (BASE - CHAMPS COMMUNS UNIQUEMENT)
-- ====================================================================================
CREATE TABLE UTILISATEUR (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(100) NOT NULL,
    PRENOM VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    MOTDEPASSEHASH VARCHAR(255) NOT NULL,
    DATECREATION DATETIME DEFAULT CURRENT_TIMESTAMP,
    ESTACTIF BOOLEAN DEFAULT TRUE,
    TYPEUTILISATEUR ENUM('ADMINISTRATEUR', 'EMPLOYE', 'CLIENT') NOT NULL
);

-- ====================================================================================
-- TABLE EMPLOYE (HÉRITE DE UTILISATEUR)
-- ====================================================================================
CREATE TABLE EMPLOYE (
    ID INT PRIMARY KEY,
    MATRICULE VARCHAR(50) UNIQUE NOT NULL,
    DATEEMBAUCHE DATE NOT NULL,
    FOREIGN KEY (ID) REFERENCES UTILISATEUR(ID) ON DELETE CASCADE
);

-- ====================================================================================
-- TABLE CLIENT (HÉRITE DE UTILISATEUR)
-- ====================================================================================
CREATE TABLE CLIENT (
    ID INT PRIMARY KEY,
    TELEPHONE VARCHAR(20) NOT NULL,
    ADRESSE TEXT NOT NULL,
    DATEINSCRIPTION DATE NOT NULL,
    NUMEROPERMIS VARCHAR(50) UNIQUE NOT NULL,
    FOREIGN KEY (ID) REFERENCES UTILISATEUR(ID) ON DELETE CASCADE
);

-- ====================================================================================
-- TABLE VEHICULE
-- ====================================================================================
CREATE TABLE VEHICULE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MARQUE VARCHAR(100) NOT NULL,
    MODELE VARCHAR(100) NOT NULL,
    IMMATRICULATION VARCHAR(20) UNIQUE NOT NULL,
    ANNEE INT NOT NULL,
    COULEUR VARCHAR(50),
    PRIXJOURNALIER DECIMAL(10, 2) NOT NULL,
    ESTDISPONIBLE BOOLEAN DEFAULT TRUE,
    KILOMETRAGE INT DEFAULT 0,
    IMAGEPRINCIPALEURL TEXT,
    IMAGESURLS JSON,
    TYPEVEHICULEID INT NOT NULL,
    DATEAJOUT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TYPEVEHICULEID) REFERENCES TYPEVEHICULE(ID) ON DELETE RESTRICT
);

-- ====================================================================================
-- TABLE LOCATION (AVEC FACTUREURL ET QRCODE)
-- ====================================================================================
CREATE TABLE LOCATION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATEDEBUT DATETIME NOT NULL,
    DATEFIN DATETIME NOT NULL,
    DUREEJOURS INT NOT NULL,
    MONTANTTOTAL DECIMAL(10, 2) NOT NULL,
    STATUT ENUM('EN_ATTENTE', 'CONFIRMEE', 'EN_COURS', 'TERMINEE', 'ANNULEE') DEFAULT 'EN_ATTENTE',
    QRCODE TEXT,
    FACTUREURL TEXT,
    CLIENTID INT NOT NULL,
    VEHICULEID INT NOT NULL,
    EMPLOYEID INT NULL,
    DATECREATION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CLIENTID) REFERENCES CLIENT(ID) ON DELETE RESTRICT,
    FOREIGN KEY (VEHICULEID) REFERENCES VEHICULE(ID) ON DELETE RESTRICT,
    FOREIGN KEY (EMPLOYEID) REFERENCES EMPLOYE(ID) ON DELETE SET NULL
);

-- ====================================================================================
-- TABLE PAIEMENT
-- ====================================================================================
CREATE TABLE PAIEMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MONTANT DECIMAL(10, 2) NOT NULL,
    DATEPAIEMENT DATETIME NOT NULL,
    MODEPAIEMENT ENUM('CARTE_CREDIT', 'VIREMENT', 'ESPECES') NOT NULL,
    STATUT ENUM('EN_ATTENTE', 'VALIDE', 'ECHOUE', 'REMBOURSE') DEFAULT 'EN_ATTENTE',
    REFERENCE VARCHAR(100) UNIQUE,
    LOCATIONID INT NOT NULL,
    DATECREATION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LOCATIONID) REFERENCES LOCATION(ID) ON DELETE CASCADE
);

-- ====================================================================================
-- TABLE ENTRETIEN
-- ====================================================================================
CREATE TABLE ENTRETIEN (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATEENTRETIEN DATETIME NOT NULL,
    TYPEENTRETIEN ENUM('REVISION_PERIODIQUE', 'REPARATION_MECANIQUE', 'REMPLACEMENT_PNEUS', 'VIDANGE',
        'CONTROLE_TECHNIQUE', 'NETTOYAGE', 'REPARATION_CARROSSERIE') NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    COUT DECIMAL(10, 2) NOT NULL,
    PROCHAINENTRETIEN DATETIME,
    ESTURGENT BOOLEAN DEFAULT FALSE,
    STATUT ENUM('PLANIFIE', 'EN_COURS', 'TERMINE', 'ANNULE') DEFAULT 'PLANIFIE',
    VEHICULEID INT NOT NULL,
    EMPLOYEID INT NULL,
    DATECREATION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VEHICULEID) REFERENCES VEHICULE(ID) ON DELETE CASCADE,
    FOREIGN KEY (EMPLOYEID) REFERENCES EMPLOYE(ID) ON DELETE SET NULL
);

-- ====================================================================================
-- TABLE RAPPORT
-- ====================================================================================
CREATE TABLE RAPPORT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TYPERAPPORT ENUM('LOCATIONS_MENSUELLES', 'REVENUS_FINANCIERS', 'PERFORMANCE_VEHICULES',
        'ACTIVITE_CLIENTS', 'ENTRETIENS_PENDANT', 'STATISTIQUES_GLOBALES') NOT NULL,
    DATEGENERATION DATETIME DEFAULT CURRENT_TIMESTAMP,
    DONNEES JSON NOT NULL,
    FORMAT ENUM('PDF', 'EXCEL', 'CSV') DEFAULT 'PDF',
    ADMINISTRATEURID INT NOT NULL,
    NOMFICHIER VARCHAR(255),
    FOREIGN KEY (ADMINISTRATEURID) REFERENCES UTILISATEUR(ID) ON DELETE CASCADE
);

